language: r
r:
  - devel
  - release
latex: false

cache:
  - packages
  - ccache

warnings_are_errors: false

r_build_args: '--no-build-vignettes'
r_check_args: '--ignore-vignettes'

r_github_packages:
  - macartan/CausalQueries

addons:
  apt:
    packages:
      - libudunits2-dev
      - libgdal-dev
      - libproj-dev
      - g++-7
      - libv8-dev
before_install:
  - mkdir -p ~/.R
  - echo "PKG_CPPFLAG=-DBOOST_NO_AUTO_PTR" >> ~/.R/Makevars
  - echo "CXX14FLAGS=-O3 -mtune=native -march=native -Wno-unused -Wno-deprecated-declarations" >> ~/.R/Makevars
  - echo "CXX14=g++ -std=c++1y -fext-numeric-literals -fPIC" >> ~/.R/Makevars

after_success:
  - tar -C .. -xf $PKG_TARBALL
  - Rscript -e 'covr::coveralls()'
